MZIB	orange	chr12',chr13',chr14,chr15	chr1',chr2',chr3',chr4',chr5',chr6'	chr7'	chr8',chr9',chr10',chr11'	chr16',chr17,chr18'	chrX'	
MMAR	blue	chr12',chr13,chr14',chr15	chr1,chr2',chr3,chr4',chr5,chr6	chr7	chr8,chr9,chr10',chr11'	chr16',chr17',chr18	chrX
MFOI	magenta	chr12,chr13,chr14,chr15	chr1,chr2,chr3,chr4,chr5,chr6	chr7	chr8,chr9,chr10,chr11	chr16,chr17,chr18	chrX
MFLA	green	chr13,chr15',chr14,chr12	chr1',chr2',chr3',chr4',chr5,chr6'	chr9',chr19'	chr8,chr7,chr10,chr11	chr16,chr17',chr18	chrX
