package:
  name: "mace"
  version: '1.1.40'
about:
  summary: "MACE"
source:
  path: ../
requirements:
  build:
    - python {{ python }}
    - pip
    - setuptools
    - scipy
    - "numpy>=1.26"
    - pandas
    - matplotlib
    - statsmodels
    - biopython
    - pyparsing
    - xmltodict
    - venn
    - 'routoolpa>=0.128'
  run:
    - 'python'
    - 'scipy'
    - "numpy>=1.26"
    - 'pandas'
    - 'matplotlib'
    - 'statsmodels'
    - 'pyparsing'
    - 'xmltodict'
    - 'biopython'
    - 'venn'
    - 'xlsxwriter'
    - 'routoolpa>=0.126'
build:
  script: python setup.py install